wandb_version: 1

lr:
  desc: null
  value: 0.001
betas:
  desc: null
  value:
  - 0.9
  - 0.999
weight_decay:
  desc: null
  value: 0.01
warmup_steps:
  desc: null
  value: 10000
with_cuda:
  desc: null
  value: true
cuda_devices:
  desc: null
  value: null
log_freq:
  desc: null
  value: 10
vocab_size:
  desc: null
  value: 30000
hidden:
  desc: null
  value: 256
layers:
  desc: null
  value: 8
attn_heads:
  desc: null
  value: 8
model:
  desc: null
  value: BERT
model Parameters:
  desc: null
  value: 21709362
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1714511098.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.11.4
      5: 0.16.4
      6: 4.40.1
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
